export const skills = [
    {
        id: "gut",
        firstPerson: /^You rip into (?<target>.+?) with your massive, deadly claws\.$/,
        secondPerson: false,
        thirdPerson: /^(?<user>\w+?) rips into (?<target>.+?) with \w+ massive, deadly claws\.$/,
        profession: "dragon",
        skill: "dragoncraft",
        balance: "balance",
        afflictions: [],
        length: 3.0,
    },
    {
        id: "incantation",
        firstPerson: /^Drawing from the well of your puissance, you invoke a dramatic chant in the dragon tongue. Your voice resonates with each word, culminating in a wave of magical energy that you bend to your will and thrust towards (?<target>.+), bombarding \w+ with the ancient power\.$/,
        secondPerson: false,
        thirdPerson: /^A resonant vibration emanates from (?<user>\w+) as \w+ invokes a rumbling, sonorous chant in the dragon tongue. As the sound increases, (?<target>.+) jerks violently, \w+ body wracked by an unseen force\.$/,
        profession: "dragon",
        skill: "dragoncraft",
        balance: "equilibrium",
        afflictions: [],
        length: 3.0,
    },
    {
        id: "glaciate",
        firstPerson: /^You breathe a column of icy air at (?<target>.+)'s head, stunning \w+\.$/,
        secondPerson: false,
        thirdPerson: false,
        profession: "dragon",
        skill: "attainment",
        balance: "battlerage",
        afflictions: ['stun'],
        length: 3.0,
    },
]